### ISSUE TITLE
considering the use of magic method __set , __unset , __isset , __get

### ISSUE THREAD

**Issue by KTP95** [carpediem/JSend#1]
so like here https://github.com/alexei/php-jsend/blob/master/JSend.php
this for alowed so like this

$success = JSend::success($data);
$success->myvar = 'hello world jsend';
$success->send();

**Comment by ignace-dev** [comment]
@KTP95 JSend is an [immutable value object](http://blog.joefallon.net/2015/08/immutable-objects-in-php/) as such adding PHP's magic setters is out of scope for the library.

With the current library you can already do this

``` php
$data = ['myvar' => 'hellow world jsend'];
$success = JSend::success($data);
echo $success->getData()['myvar']; //will return 'hello world Jsend' 
$success->send();
```

or do this

``` php
$success = Jsend::success([]);
$data = ['myvar' => 'hellow world jsend'];
$success = $success->withData($data);
echo $success->getData()['myvar']; //will return 'hello world Jsend' 
$success->send();
```
